// This file was autogenerated by bower_components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/javascript/util/ArrayList.js', ['javascript.util.ArrayList'], ['javascript.util.Collection', 'javascript.util.IndexOutOfBoundsException', 'javascript.util.Iterator', 'javascript.util.List', 'javascript.util.NoSuchElementException', 'javascript.util.OperationNotSupported'], false);
goog.addDependency('../../../../src/javascript/util/Arrays.js', ['javascript.util.Arrays'], ['javascript.util.ArrayList'], false);
goog.addDependency('../../../../src/javascript/util/Collection.js', ['javascript.util.Collection'], ['javascript.util.Iterator'], false);
goog.addDependency('../../../../src/javascript/util/EmptyStackException.js', ['javascript.util.EmptyStackException'], [], false);
goog.addDependency('../../../../src/javascript/util/HashMap.js', ['javascript.util.HashMap'], ['javascript.util.ArrayList', 'javascript.util.Map'], false);
goog.addDependency('../../../../src/javascript/util/HashSet.js', ['javascript.util.HashSet'], ['javascript.util.Collection', 'javascript.util.Iterator', 'javascript.util.NoSuchElementException', 'javascript.util.OperationNotSupported', 'javascript.util.Set'], false);
goog.addDependency('../../../../src/javascript/util/IndexOutOfBoundsException.js', ['javascript.util.IndexOutOfBoundsException'], [], false);
goog.addDependency('../../../../src/javascript/util/Iterator.js', ['javascript.util.Iterator'], [], false);
goog.addDependency('../../../../src/javascript/util/List.js', ['javascript.util.List'], ['javascript.util.Collection'], false);
goog.addDependency('../../../../src/javascript/util/Map.js', ['javascript.util.Map'], [], false);
goog.addDependency('../../../../src/javascript/util/NoSuchElementException.js', ['javascript.util.NoSuchElementException'], [], false);
goog.addDependency('../../../../src/javascript/util/OperationNotSupported.js', ['javascript.util.OperationNotSupported'], [], false);
goog.addDependency('../../../../src/javascript/util/Set.js', ['javascript.util.Set'], ['javascript.util.Collection'], false);
goog.addDependency('../../../../src/javascript/util/SortedMap.js', ['javascript.util.SortedMap'], ['javascript.util.Map'], false);
goog.addDependency('../../../../src/javascript/util/SortedSet.js', ['javascript.util.SortedSet'], ['javascript.util.Set'], false);
goog.addDependency('../../../../src/javascript/util/Stack.js', ['javascript.util.Stack'], ['javascript.util.EmptyStackException', 'javascript.util.List'], false);
goog.addDependency('../../../../src/javascript/util/TreeMap.js', ['javascript.util.TreeMap'], ['javascript.util.ArrayList', 'javascript.util.SortedMap'], false);
goog.addDependency('../../../../src/javascript/util/TreeSet.js', ['javascript.util.TreeSet'], ['javascript.util.Collection', 'javascript.util.Iterator', 'javascript.util.NoSuchElementException', 'javascript.util.OperationNotSupported', 'javascript.util.SortedSet'], false);
