/*
  javascript.util is a port of selected parts of java.util to JavaScript which
  main purpose is to ease porting Java code to JavaScript.
  
  The MIT License (MIT)

  Copyright (C) 2011,2012 by The Authors

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

javascript={util:{}};if(typeof module!=='undefined'){module.exports=javascript;}
(function(){function EmptyStackException(message){this.message=message||'';};EmptyStackException.prototype=new Error();EmptyStackException.prototype.name='EmptyStackException';javascript.util.EmptyStackException=EmptyStackException;})();(function(){function IndexOutOfBoundsException(message){this.message=message||'';};IndexOutOfBoundsException.prototype=new Error();IndexOutOfBoundsException.prototype.name='IndexOutOfBoundsException';javascript.util.IndexOutOfBoundsException=IndexOutOfBoundsException;})();(function(){function NoSuchElementException(message){this.message=message||'';};NoSuchElementException.prototype=new Error();NoSuchElementException.prototype.name='NoSuchElementException';javascript.util.NoSuchElementException=NoSuchElementException;})();(function(){function OperationNotSupported(message){this.message=message||'';};OperationNotSupported.prototype=new Error();OperationNotSupported.prototype.name='OperationNotSupported';javascript.util.OperationNotSupported=OperationNotSupported;})();(function(){function Map(){};Map.prototype.get=function(key){};Map.prototype.put=function(key,value){};Map.prototype.size=function(){};Map.prototype.values=function(){};javascript.util.Map=Map;})();(function(){var Map=javascript.util.Map;function SortedMap(){};SortedMap.prototype=new Map;javascript.util.SortedMap=SortedMap;})();(function(){function Arrays(){};Arrays.sort=function(){var a=arguments[0],i,t,comparator,compare;if(arguments.length===1){a.sort();return;}else if(arguments.length===2){comparator=arguments[1];compare=function(a,b){return comparator['compare'](a,b);};a.sort(compare);}else if(arguments.length===3){t=a.slice(arguments[1],arguments[2]);t.sort();var r=a.slice(0,arguments[1]).concat(t,a.slice(arguments[2],a.length));a.splice(0,a.length);for(i=0;i<r.length;i++){a.push(r[i]);}
return;}else if(arguments.length===4){t=a.slice(arguments[1],arguments[2]);comparator=arguments[3];compare=function(a,b){return comparator['compare'](a,b);};t.sort(compare);r=a.slice(0,arguments[1]).concat(t,a.slice(arguments[2],a.length));a.splice(0,a.length);for(i=0;i<r.length;i++){a.push(r[i]);}
return;}};Arrays.asList=function(array){var arrayList=new javascript.util.ArrayList();for(var i=0,len=array.length;i<len;i++){arrayList.add(array[i]);}
return arrayList;};javascript.util.Arrays=Arrays;})();(function(){function Iterator(){};Iterator.prototype.hasNext=function(){};Iterator.prototype.next=function(){};Iterator.prototype.remove=function(){};javascript.util.Iterator=Iterator;})();(function(){var Iterator=javascript.util.Iterator;function Collection(){};Collection.prototype.add=function(o){};Collection.prototype.addAll=function(c){};Collection.prototype.isEmpty=function(){};Collection.prototype.iterator=function(){};Collection.prototype.size=function(){};Collection.prototype.toArray=function(){};Collection.prototype.remove=function(o){};javascript.util.Collection=Collection;})();(function(){var Collection=javascript.util.Collection;function List(){};List.prototype=new Collection;List.prototype.get=function(index){};List.prototype.set=function(index,element){};List.prototype.isEmpty=function(){};javascript.util.List=List;})();(function(){var Collection=javascript.util.Collection;var List=javascript.util.List;var OperationNotSupported=javascript.util.OperationNotSupported;var NoSuchElementException=javascript.util.NoSuchElementException;var IndexOutOfBoundsException=javascript.util.IndexOutOfBoundsException;function ArrayList(){this.array=[];if(arguments[0]instanceof Collection){this.addAll(arguments[0]);}};ArrayList.prototype=new List;ArrayList.prototype.array=null;ArrayList.prototype.add=function(e){this.array.push(e);return true;};ArrayList.prototype.addAll=function(c){for(var i=c.iterator();i.hasNext();){this.add(i.next());}
return true;};ArrayList.prototype.set=function(index,element){var oldElement=this.array[index];this.array[index]=element;return oldElement;};ArrayList.prototype.iterator=function(){return new ArrayList.Iterator(this);};ArrayList.prototype.get=function(index){if(index<0||index>=this.size()){throw new IndexOutOfBoundsException();}
return this.array[index];};ArrayList.prototype.isEmpty=function(){return this.array.length===0;};ArrayList.prototype.size=function(){return this.array.length;};ArrayList.prototype.toArray=function(){var array=[];for(var i=0,len=this.array.length;i<len;i++){array.push(this.array[i]);}
return array;};ArrayList.prototype.remove=function(o){var found=false;for(var i=0,len=this.array.length;i<len;i++){if(this.array[i]===o){this.array.splice(i,1);found=true;break;}}
return found;};ArrayList.Iterator=function(arrayList){this.arrayList=arrayList;};ArrayList.Iterator.prototype.arrayList=null;ArrayList.Iterator.prototype.position=0;ArrayList.Iterator.prototype.next=function(){if(this.position===this.arrayList.size()){throw new NoSuchElementException();}
return this.arrayList.get(this.position++);};ArrayList.Iterator.prototype.hasNext=function(){if(this.position<this.arrayList.size()){return true;}
return false;};ArrayList.Iterator.prototype.remove=function(){throw new OperationNotSupported();};javascript.util.ArrayList=ArrayList;})();(function(){var Map=javascript.util.Map;var ArrayList=javascript.util.ArrayList;function HashMap(){this.object={};};HashMap.prototype=new Map;HashMap.prototype.object=null;HashMap.prototype.get=function(key){return this.object[key]||null;};HashMap.prototype.put=function(key,value){this.object[key]=value;return value;};HashMap.prototype.values=function(){var arrayList=new javascript.util.ArrayList();for(var key in this.object){if(this.object.hasOwnProperty(key)){arrayList.add(this.object[key]);}}
return arrayList;};HashMap.prototype.size=function(){return this.values().size();};javascript.util.HashMap=HashMap;})();(function(){var Collection=javascript.util.Collection;function Set(){};Set.prototype=new Collection;Set.prototype.contains=function(o){};javascript.util.Set=Set;})();(function(){var Set=javascript.util.Set;function SortedSet(){};SortedSet.prototype=new Set;javascript.util.SortedSet=SortedSet;})();(function(){var Collection=javascript.util.Collection;var SortedSet=javascript.util.SortedSet;var OperationNotSupported=javascript.util.OperationNotSupported;var NoSuchElementException=javascript.util.NoSuchElementException;function TreeSet(){this.array=[];if(arguments[0]instanceof Collection){this.addAll(arguments[0]);}};TreeSet.prototype=new SortedSet;TreeSet.prototype.array=null;TreeSet.prototype.contains=function(o){for(var i=0,len=this.array.length;i<len;i++){var e=this.array[i];if(e['compareTo'](o)===0){return true;}}
return false;};TreeSet.prototype.add=function(o){if(this.contains(o)){return false;}
for(var i=0,len=this.array.length;i<len;i++){var e=this.array[i];if(e['compareTo'](o)===1){this.array.splice(i,0,o);return true;}}
this.array.push(o);return true;};TreeSet.prototype.addAll=function(c){for(var i=c.iterator();i.hasNext();){this.add(i.next());}
return true;};TreeSet.prototype.remove=function(o){throw new OperationNotSupported();};TreeSet.prototype.size=function(){return this.array.length;};TreeSet.prototype.isEmpty=function(){return this.array.length===0;};TreeSet.prototype.toArray=function(){var array=[];for(var i=0,len=this.array.length;i<len;i++){array.push(this.array[i]);}
return array;};TreeSet.prototype.iterator=function(){return new TreeSet.Iterator(this);};TreeSet.Iterator=function(treeSet){this.treeSet=treeSet;};TreeSet.Iterator.prototype.treeSet=null;TreeSet.Iterator.prototype.position=0;TreeSet.Iterator.prototype.next=function(){if(this.position===this.treeSet.size()){throw new NoSuchElementException();}
return this.treeSet.array[this.position++];};TreeSet.Iterator.prototype.hasNext=function(){if(this.position<this.treeSet.size()){return true;}
return false;};TreeSet.Iterator.prototype.remove=function(){throw new javascript.util.OperationNotSupported();};javascript.util.TreeSet=TreeSet;})();(function(){var List=javascript.util.List;var EmptyStackException=javascript.util.EmptyStackException;function Stack(){this.array=[];};Stack.prototype=new List;Stack.prototype.array=null;Stack.prototype.push=function(e){this.array.push(e);return e;};Stack.prototype.pop=function(e){if(this.array.length===0){throw new EmptyStackException();}
return this.array.pop();};Stack.prototype.peek=function(){if(this.array.length===0){throw new EmptyStackException();}
return this.array[this.array.length-1];};Stack.prototype.empty=function(e){if(this.array.length===0){return true;}else{return false;}};Stack.prototype.isEmpty=function(){return this.empty();};Stack.prototype.search=function(o){return this.array.indexOf(o);};Stack.prototype.size=function(){return this.array.length;};Stack.prototype.toArray=function(){var array=[];for(var i=0,len=this.array.length;i<len;i++){array.push(this.array[i]);}
return array;};javascript.util.Stack=Stack;})();(function(){var Map=javascript.util.Map;var SortedMap=javascript.util.SortedMap;var ArrayList=javascript.util.ArrayList;function TreeMap(){this.array=[];};TreeMap.prototype=new Map;TreeMap.prototype.array=null;TreeMap.prototype.get=function(key){for(var i=0,len=this.array.length;i<len;i++){var e=this.array[i];if(e.key['compareTo'](key)===0){return e.value;}}
return null;};TreeMap.prototype.put=function(key,value){var e=this.get(key);if(e){var oldValue=e.value;e.value=value;return oldValue;}
var newElement={key:key,value:value};for(var i=0,len=this.array.length;i<len;i++){e=this.array[i];if(e.key['compareTo'](key)===1){this.array.splice(i,0,newElement);return null;}}
this.array.push({key:key,value:value});return null;};TreeMap.prototype.values=function(){var arrayList=new javascript.util.ArrayList();for(var i=0,len=this.array.length;i<len;i++){arrayList.add(this.array[i].value);}
return arrayList;};TreeMap.prototype.size=function(){return this.values().size();};javascript.util.TreeMap=TreeMap;})();(function(){var Collection=javascript.util.Collection;var Set=javascript.util.Set;var OperationNotSupported=javascript.util.OperationNotSupported;var NoSuchElementException=javascript.util.NoSuchElementException;function HashSet(){this.array=[];if(arguments[0]instanceof Collection){this.addAll(arguments[0]);}};HashSet.prototype=new Set;HashSet.prototype.array=null;HashSet.prototype.contains=function(o){for(var i=0,len=this.array.length;i<len;i++){var e=this.array[i];if(e===o){return true;}}
return false;};HashSet.prototype.add=function(o){if(this.contains(o)){return false;}
this.array.push(o);return true;};HashSet.prototype.addAll=function(c){for(var i=c.iterator();i.hasNext();){this.add(i.next());}
return true;};HashSet.prototype.remove=function(o){throw new OperationNotSupported();};HashSet.prototype.size=function(){return this.array.length;};HashSet.prototype.isEmpty=function(){return this.array.length===0;};HashSet.prototype.toArray=function(){var array=[];for(var i=0,len=this.array.length;i<len;i++){array.push(this.array[i]);}
return array;};HashSet.prototype.iterator=function(){return new HashSet.Iterator(this);};HashSet.Iterator=function(hashSet){this.hashSet=hashSet;};HashSet.Iterator.prototype.hashSet=null;HashSet.Iterator.prototype.position=0;HashSet.Iterator.prototype.next=function(){if(this.position===this.hashSet.size()){throw new NoSuchElementException();}
return this.hashSet.array[this.position++];};HashSet.Iterator.prototype.hasNext=function(){if(this.position<this.hashSet.size()){return true;}
return false;};HashSet.Iterator.prototype.remove=function(){throw new javascript.util.OperationNotSupported();};javascript.util.HashSet=HashSet;})();